# Generated by Django 5.0.3 on 2024-04-03 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_plate', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('seats', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['num_plate'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=80)),
                ('seat', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('departure', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Full', 'Full'), ('Boarding', 'Boarding'), ('In Transit', 'In Transit'), ('Cancelled', 'Cancelled')], default='Boarding', max_length=20)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twasonga.bus')),
            ],
            options={
                'ordering': ['customer'],
            },
        ),
    ]
