# Generated by Django 5.0.3 on 2024-04-25 11:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twasonga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='route',
            field=models.CharField(choices=[('1', 'Nairobi-Makongeni'), ('2', 'Nairobi-Thika'), ('3', 'Nairobi-Juja'), ('4', 'Nairobi-Kikuyu'), ('5', 'Nairobi-Kitengela')], default='Nairobi-Juja', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
